@ECHO OFF
SET ALLUSERSPROFILE=C:\Documents and Settings\All Users
SET APPDATA=C:\Documents and Settings\chrisc\Application Data
SET APR_ICONV_PATH=E:\Program Files\Subversion\iconv
@ECHO OFF
SET CLASSPATH=.;E:\Program Files\Java\jre6\lib\ext\QTJava.zip
SET CLIENTNAME=Console
SET COMMONPROGRAMFILES=C:\Program Files\Common Files
SET COMPUTERNAME=HAMSTER
SET COMSPEC=C:\WINDOWS\system32\cmd.exe
SET CVS_RSH=/bin/ssh
SET DD=/e/home/develop/code/cyg-apt
SET EDITOR=vi
SET FP_NO_HOST_CHECK=NO
SET GTK_BASEPATH=e:\GTK
SET HOMEDRIVE=C:
SET HOMEPATH=\Documents and Settings\chrisc
SET LOGONSERVER=\\HAMSTER
SET NUMBER_OF_PROCESSORS=2
SET OS=Windows_NT
SET PATH=E:\msys\1.0\local\bin;E:\MinGW\bin;E:\Program Files\Snapshot;E:\home\develop\code\cyg-apt;e:\GTK\bin;e:\Program Files\Bin;e:\Python26;E:\Program Files\Windows Resource Kits\Tools\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\Program Files\Common Files\DivX Shared\;E:\Program Files\QuickTime\QTSystem\;E:\Program Files\Subversion\bin
SET PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH
SET PROCESSOR_ARCHITECTURE=x86
SET PROCESSOR_IDENTIFIER=x86 Family 6 Model 15 Stepping 11, GenuineIntel
SET PROCESSOR_LEVEL=6
SET PROCESSOR_REVISION=0f0b
SET PROGRAMFILES=C:\Program Files
SET PROMPT=$P$G
SET QTJAVA=E:\Program Files\Java\jre6\lib\ext\QTJava.zip
SET SESSIONNAME=Console
SET SHLVL=1
SET SVN_EDITOR=vi
SET SYSTEMDRIVE=C:
SET SYSTEMROOT=C:\WINDOWS
SET TEMP=C:\DOCUME~1\chrisc\LOCALS~1\Temp
SET TMP=C:\DOCUME~1\chrisc\LOCALS~1\Temp
SET USERDOMAIN=HAMSTER
SET USERNAME=chrisc
SET USERPROFILE=C:\Documents and Settings\chrisc
SET VBOX_INSTALL_PATH=E:\Program Files\VirtualBox\
SET VS80COMNTOOLS=E:\vs\Common7\Tools\
SET WINDIR=C:\WINDOWS
SET _=/c/WINDOWS/system32/cmd
SET tvdumpflags=8
